### ISSUE TITLE
更新油猴商店的版本为v0.4

### ISSUE THREAD

**Issue by CC11001100** [JSREI/jQuery-hook#1]
油猴商店上架地址： https://greasyfork.org/zh-CN/scripts/435556-jquery-hook

**Comment by dingcang** [comment]
大佬什么时候更新0.4版本到商店，现在还是0.3版本的。

**Comment by CC11001100** [comment]
> 大佬什么时候更新0.4版本到商店，现在还是0.3版本的。

感谢老哥的支持，油猴商店的版本已经更新到了0.4版本啦
